USE [BDSinAlitas]
GO

/****** Object:  Table [dbo].[CCA_CANCELACION_CLASE]    Script Date: 26-10-2016 15:06:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CCA_CANCELACION_CLASE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FECHA_CANCELACION] [datetime] NULL,
	[PCO_ID] [int] NULL,
	[CPO_ID] [int] NULL,
	[PROF_ID] [int] NULL,
	[MOTIVO] [varchar](500) NULL,
 CONSTRAINT [PK_CCA_CANCELACION_CLASE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

