alter table prof_profesor add COM_ID_ASIGNADA VARCHAR(250) NULL

UPDATE PROF_PROFESOR SET COM_ID_ASIGNADA = '*'

GO

/****** Object:  Table [dbo].[PRO_PRODUCTO]    Script Date: 23-08-2016 22:40:51 ******/
DROP TABLE [dbo].[PRO_PRODUCTO]
GO

/****** Object:  Table [dbo].[PRO_PRODUCTO]    Script Date: 23-08-2016 22:40:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PRO_PRODUCTO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](250) NULL,
	[DESCRIPCION] [varchar](500) NULL,
	[PRECIO] [int] NULL,
	[CANTIDAD_ALUMNOS] [int] NULL,
	[ELIMINADO] [int] NULL,
	[ACTIVO] [int] NULL,
 CONSTRAINT [PK_PRO_PRODUCTO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[PCO_PRODUCTO_CODIGO]    Script Date: 23-08-2016 23:47:01 ******/
DROP TABLE [dbo].[PCO_PRODUCTO_CODIGO]
GO

/****** Object:  Table [dbo].[PCO_PRODUCTO_CODIGO]    Script Date: 23-08-2016 23:47:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PCO_PRODUCTO_CODIGO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CODIGO_CLIENTE] [varchar](250) NULL,
	[CLIE_ID] [int] NULL,
	[PRO_ID] [int] NULL,
	[CANTIDAD_CLASES] [INT] NULL,
	[ACTIVO] [int] NULL,
	[ELIMINADO] [int] NULL,
 CONSTRAINT [PK_PCO_PRODUCTO_CODIGO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


