alter table pco_producto_codigo add CANTIDAD_ALUMNOS INT 
GO
alter table pco_producto_codigo add ESTADO INT 
GO
alter table pco_producto_codigo add FECHA_CREACION DATETIME 
GO

/****** Object:  Table [dbo].[FIP_FICHA_PACK]    Script Date: 27-09-2016 15:18:03 ******/
DROP TABLE [dbo].[FIP_FICHA_PACK]
GO

/****** Object:  Table [dbo].[FIP_FICHA_PACK]    Script Date: 27-09-2016 15:18:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FIP_FICHA_PACK](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_PACK] [int] NULL,
	[ID_ALUMNO] [int] NULL,
	[FECHA_CREACION] [datetime] NULL,
	[ACTIVO] [int] NULL,
	[ELIMINADO] [int] NULL,
 CONSTRAINT [PK_FIP_FICHA_PACK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


/****** Object:  Table [dbo].[ACC_ACEPTA_CONDICIONES]    Script Date: 27-09-2016 19:05:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ACC_ACEPTA_CONDICIONES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PCO_ID] [int] NULL,
	[FECHA_ACEPTA] [datetime] NULL,
	[ES_ACEPTADO] [int] NULL,
	[ES_COMPLETADO] [int] NULL,
	[ACTIVO] [int] NULL,
 CONSTRAINT [PK_ACC_ACEPTA_CONDICIONES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

