USE [BDSinAlitas]
GO
/****** Object:  Table [dbo].[SGH_SEGMENTO_HORARIO]    Script Date: 04-08-2016 16:27:27 ******/
DROP TABLE [dbo].[SGH_SEGMENTO_HORARIO]
GO
/****** Object:  Table [dbo].[REG_REGION]    Script Date: 04-08-2016 16:27:27 ******/
DROP TABLE [dbo].[REG_REGION]
GO
/****** Object:  Table [dbo].[PROF_PROFESOR]    Script Date: 04-08-2016 16:27:27 ******/
DROP TABLE [dbo].[PROF_PROFESOR]
GO
/****** Object:  Table [dbo].[PAI_PAIS]    Script Date: 04-08-2016 16:27:27 ******/
DROP TABLE [dbo].[PAI_PAIS]
GO
/****** Object:  Table [dbo].[NOD_NODO]    Script Date: 04-08-2016 16:27:27 ******/
DROP TABLE [dbo].[NOD_NODO]
GO
/****** Object:  Table [dbo].[CPO_CUPO]    Script Date: 04-08-2016 16:27:27 ******/
DROP TABLE [dbo].[CPO_CUPO]
GO
/****** Object:  Table [dbo].[COM_COMUNA]    Script Date: 04-08-2016 16:27:27 ******/
DROP TABLE [dbo].[COM_COMUNA]
GO
/****** Object:  Table [dbo].[CLIE_CLIENTE]    Script Date: 04-08-2016 16:27:27 ******/
DROP TABLE [dbo].[CLIE_CLIENTE]
GO
/****** Object:  Table [dbo].[AGP_AGENDA_PROFESOR]    Script Date: 04-08-2016 16:27:27 ******/
DROP TABLE [dbo].[AGP_AGENDA_PROFESOR]
GO
/****** Object:  Table [dbo].[AGP_AGENDA_PROFESOR]    Script Date: 04-08-2016 16:27:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AGP_AGENDA_PROFESOR](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PROF_ID] [int] NULL,
	[NOD_ID] [int] NULL,
	[FECHA_HORA_INICIO] [datetime] NULL,
	[FECHA_HORA_TERMINO] [datetime] NULL,
	[ACTIVO] [int] NULL,
	[ELIMINADO] [int] NULL,
 CONSTRAINT [PK_AGP_AGENDA_PROFESOR] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[CLIE_CLIENTE]    Script Date: 04-08-2016 16:27:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CLIE_CLIENTE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PAI_ID] [int] NULL,
	[RUT] [varchar](50) NULL,
	[NOMBRES] [varchar](150) NULL,
	[PRIMER_APELLIDO] [varchar](150) NULL,
	[SEGUNDO_APELLIDO] [varchar](150) NULL,
	[CODIGO] [varchar](150) NULL,
	[REG_ID] [int] NULL,
	[COM_ID] [int] NULL,
	[DIRECCION] [varchar](500) NULL,
	[SEXO] [varchar](50) NULL,
	[NOMBRE_USUARIO] [varchar](150) NULL,
	[PASSWORD] [varchar](50) NULL,
	[ACTIVO] [int] NULL,
	[ELIMINADO] [int] NULL,
	[TELEFONOS_CONTACTO] [varchar](250) NULL,
	[EMAIL] [varchar](250) NULL,
	[NOD_ID] [int] NULL,
 CONSTRAINT [PK_CLIE_CLIENTE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[COM_COMUNA]    Script Date: 04-08-2016 16:27:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[COM_COMUNA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[REG_ID] [int] NULL,
	[NOMBRE] [varchar](250) NULL,
	[ELIMINADO] [int] NULL,
 CONSTRAINT [PK_COM_COMUNA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[CPO_CUPO]    Script Date: 04-08-2016 16:27:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CPO_CUPO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SGH_ID] [int] NULL,
	[FECHA_HORA_INICIO] [datetime] NULL,
	[FECHA_HORA_TERMINO] [datetime] NULL,
	[ESTADO_CUPO] [int] NULL,
	[DESCRIPCION] [varchar](500) NULL,
	[ELIMINADO] [int] NULL,
	[ACTIVO] [int] NULL,
	[NOD_ID] [int] NULL,
	[PROF_ID] [int] NULL,
	[CLIE_ID] [int] NULL,
	[FECHA_HORA_REGISTRO] [datetime] NULL,
 CONSTRAINT [PK_CPO_CUPO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[NOD_NODO]    Script Date: 04-08-2016 16:27:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[NOD_NODO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](250) NULL,
	[DIRECCION] [varchar](500) NULL,
	[PAI_ID] [int] NULL,
	[REG_ID] [int] NULL,
	[COM_ID] [int] NULL,
	[EMAIL] [varchar](150) NULL,
	[TELEFONO_CONTACTO_1] [varchar](50) NULL,
	[TELEFONO_CONTACTO_2] [varchar](50) NULL,
	[ACTIVO] [int] NULL,
	[ELIMINADO] [int] NULL,
 CONSTRAINT [PK_NOD_NODO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PAI_PAIS]    Script Date: 04-08-2016 16:27:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PAI_PAIS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](250) NULL,
	[ELIMINADO] [int] NULL,
 CONSTRAINT [PK_PAI_PAIS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PROF_PROFESOR]    Script Date: 04-08-2016 16:27:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PROF_PROFESOR](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[RUT] [varchar](50) NULL,
	[NOMBRES] [varchar](150) NULL,
	[PRIMER_APELLIDO] [varchar](150) NULL,
	[SEGUNDO_APELLIDO] [varchar](150) NULL,
	[FOTOGRAFIA] [varchar](500) NULL,
	[CODIGO] [varchar](150) NULL,
	[PAI_ID] [int] NULL,
	[REG_ID] [int] NULL,
	[COM_ID] [int] NULL,
	[DIRECCION] [varchar](500) NULL,
	[SEXO] [varchar](50) NULL,
	[FECHA_NACIMIENTO] [datetime] NULL,
	[NOMBRE_USUARIO] [varchar](150) NULL,
	[PASSWORD] [varchar](50) NULL,
	[ACTIVO] [int] NULL,
	[ELIMINADO] [int] NULL,
	[TELEFONOS_CONTACTO] [varchar](250) NULL,
	[BANCO] [varchar](250) NULL,
	[TIPO_CUENTA] [int] NULL,
	[NUMERO_CUENTA] [varchar](250) NULL,
	[EMAIL] [varchar](250) NULL,
	[NOD_ID] [int] NULL,
 CONSTRAINT [PK_PROF_PROFESOR] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[REG_REGION]    Script Date: 04-08-2016 16:27:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[REG_REGION](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PAI_ID] [int] NULL,
	[NOMBRE] [varchar](250) NULL,
	[ELIMINADO] [int] NULL,
 CONSTRAINT [PK_REG_REGION] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[SGH_SEGMENTO_HORARIO]    Script Date: 04-08-2016 16:27:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SGH_SEGMENTO_HORARIO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOD_ID] [int] NULL,
	[DURACION_ATENCION] [int] NULL,
	[FECHA_HORA_INICIAL] [datetime] NULL,
	[FECHA_HORA_FINAL] [datetime] NULL,
	[ACTIVO] [int] NULL,
	[ELIMINADO] [int] NULL,
 CONSTRAINT [PK_SGH_SEGMENTO_HORARIO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET IDENTITY_INSERT [dbo].[CLIE_CLIENTE] ON 

GO
INSERT [dbo].[CLIE_CLIENTE] ([ID], [PAI_ID], [RUT], [NOMBRES], [PRIMER_APELLIDO], [SEGUNDO_APELLIDO], [CODIGO], [REG_ID], [COM_ID], [DIRECCION], [SEXO], [NOMBRE_USUARIO], [PASSWORD], [ACTIVO], [ELIMINADO], [TELEFONOS_CONTACTO], [EMAIL], [NOD_ID]) VALUES (1, 1, N'2535306-1', N'Victor', N'Coronado', N'Alarcón', N'vcoronado', 13, 0, N'Pasaje Cordón Roma, número 0621, Villa Entre Rios', N'Hombre', N'vcoronadocliente', N'123456', 1, 0, N'+56 9 85006988', N'vcoronado.alarcon@gmail.com', 1)
GO
SET IDENTITY_INSERT [dbo].[CLIE_CLIENTE] OFF
GO
SET IDENTITY_INSERT [dbo].[COM_COMUNA] ON 

GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (1, 13, N'No Informado', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (2, 13, N'Huechuraba', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (3, 13, N'El Bosque', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (4, 13, N'Lo Espejo', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (5, 13, N'Pedro Aguirre Cerda', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (6, 13, N'Santiago', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (7, 13, N'Estacion Central', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (8, 13, N'Maipu', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (9, 13, N'Cerrillos', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (10, 13, N'Conchalí', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (11, 13, N'Providencia', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (12, 13, N'Vitacura', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (13, 13, N'Lo Barnechea', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (14, 13, N'Las Condes', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (15, 13, N'Ñuñoa', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (16, 13, N'La Reina', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (17, 13, N'Macul', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (18, 13, N'Peñalolen', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (19, 13, N'San Joaquin', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (20, 13, N'La Granja', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (21, 13, N'La Pintana', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (22, 13, N'San Ramon', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (23, 13, N'San Miguel', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (24, 13, N'La Cisterna', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (25, 13, N'Quinta Normal', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (26, 13, N'Lo Prado', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (27, 13, N'Pudahuel', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (28, 13, N'Cerro Navia', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (29, 13, N'Renca', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (30, 13, N'Quilicura', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (31, 13, N'Recoleta', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (32, 13, N'Independencia', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (33, 13, N'La Florida', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (34, 8, N'Concepción', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (35, 8, N'Laja', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (36, 8, N'Arauco', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (37, 15, N'Arica', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (38, 15, N'Camarones', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (39, 1, N'Iquique', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (40, 1, N'Huara', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (41, 1, N'Camiña', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (42, 1, N'Colchane', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (43, 1, N'Pozo Almonte', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (44, 1, N'Pica', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (45, 15, N'Putre', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (46, 15, N'General Lagos', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (47, 2, N'Calama', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (48, 2, N'Ollagüe', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (49, 2, N'San Pedro De Atacama', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (50, 4, N'Coquimbo', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (51, 4, N'La Serena', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (52, 4, N'La Higuera', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (53, 4, N'Andacollo', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (54, 4, N'Vicuña', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (55, 4, N'Paiguano', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (56, 4, N'Ovalle', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (57, 4, N'Río Hurtado', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (58, 4, N'Monte Patria', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (59, 4, N'Punitaqui', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (60, 4, N'Combarbalá', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (61, 4, N'Illapel', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (62, 4, N'Salamanca', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (63, 4, N'Los Vilos', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (64, 4, N'Canela', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (65, 5, N'Valparaíso', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (66, 5, N'Viña Del Mar', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (67, 5, N'Quintero', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (68, 5, N'Quilpué', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (69, 5, N'Villa Alemana', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (70, 5, N'Casablanca', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (71, 5, N'Puchuncaví', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (72, 5, N'Juan Fernández', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (73, 5, N'Quillota', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (74, 5, N'La Cruz', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (75, 5, N'Calera', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (76, 5, N'Nogales', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (77, 5, N'Hijuelas', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (78, 5, N'Limache', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (79, 5, N'Olmué', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (80, 5, N'San Antonio', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (81, 5, N'Cartagena', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (82, 5, N'Santo Domingo', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (83, 5, N'El Tabo', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (84, 5, N'El Quisco', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (85, 5, N'Algarrobo', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (86, 5, N'San Felipe', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (87, 5, N'Panquehue', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (88, 5, N'Putaendo', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (89, 5, N'Santa María', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (90, 5, N'Catemu', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (91, 5, N'Llaillay', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (92, 5, N'Los Andes', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (93, 5, N'San Esteban', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (94, 5, N'Rinconada', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (95, 5, N'Calle Larga', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (96, 5, N'Petorca', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (97, 5, N'La Ligua', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (98, 5, N'Cabildo', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (99, 5, N'Zapallar', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (100, 5, N'Papudo', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (101, 5, N'Isla De Pascua', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (102, 6, N'Rancagua', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (103, 6, N'Machalí', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (104, 6, N'Graneros', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (105, 6, N'Codegua', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (106, 6, N'Mostazal', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (107, 6, N'Requínoa', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (108, 6, N'Olivar', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (109, 6, N'Rengo', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (110, 6, N'Quinta De Tilcoco', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (111, 6, N'Malloa', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (112, 6, N'San Vicente', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (113, 6, N'Doñihue', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (114, 6, N'Coinco', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (115, 6, N'Coltauco', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (116, 6, N'Pichidegua', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (117, 6, N'Peumo', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (118, 6, N'Las Cabras', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (119, 6, N'San Fernando', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (120, 6, N'Chimbarongo', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (121, 6, N'Nancagua', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (122, 6, N'Placilla', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (123, 6, N'Chépica', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (124, 6, N'Santa Cruz', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (125, 6, N'Palmilla', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (126, 6, N'Lolol', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (127, 6, N'Pumanque', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (128, 6, N'Peralillo', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (129, 6, N'Pichilemu', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (130, 6, N'Paredones', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (131, 6, N'Marchihue', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (132, 6, N'Litueche', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (133, 6, N'La Estrella', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (134, 6, N'Navidad', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (135, 7, N'Curicó', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (136, 7, N'Rauco', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (137, 7, N'Romeral', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (138, 7, N'Teno', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (139, 7, N'Vichuquén', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (140, 7, N'Licantén', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (141, 7, N'Hualañé', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (142, 7, N'Molina', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (143, 7, N'Sagrada Familia', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (144, 7, N'Talca', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (145, 7, N'San Clemente', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (146, 7, N'Pelarco', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (147, 7, N'Río Claro', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (148, 7, N'Pencahue', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (149, 7, N'Maule', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (150, 7, N'Curepto', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (151, 7, N'Constitución', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (152, 7, N'Empedrado', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (153, 7, N'Linares', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (154, 7, N'Yerbas Buenas', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (155, 7, N'Colbún', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (156, 7, N'Longaví', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (157, 7, N'Parral', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (158, 7, N'Retiro', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (159, 7, N'San Javier', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (160, 7, N'Villa Alegre', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (161, 7, N'Cauquenes', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (162, 7, N'Chanco', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (163, 7, N'Pelluhue', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (164, 8, N'Chillán', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (165, 8, N'Pinto', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (166, 8, N'Portezuelo', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (167, 8, N'San Carlos', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (168, 8, N'Ñiquén', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (169, 8, N'San Fabián', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (170, 8, N'Coihueco', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (171, 8, N'San Ignacio', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (172, 8, N'El Carmen', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (173, 8, N'Yungay', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (174, 8, N'Pemuco', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (175, 8, N'Treguaco', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (176, 8, N'Cobquecura', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (177, 8, N'Quirihue', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (178, 8, N'Ninhue', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (179, 8, N'San Nicolás', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (180, 8, N'Bulnes', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (181, 8, N'Quillón', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (182, 8, N'Coelemu', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (183, 8, N'Ránquil', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (184, 8, N'Talcahuano', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (185, 8, N'Penco', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (186, 8, N'Tomé', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (187, 8, N'Florida', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (188, 8, N'Hualqui', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (189, 8, N'Santa Juana', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (190, 8, N'Lota', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (191, 8, N'Coronel', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (192, 8, N'Los Álamos', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (193, 8, N'Cañete', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (194, 8, N'Contulmo', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (195, 8, N'San Rosendo', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (196, 8, N'Yumbel', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (197, 8, N'Tucapel', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (198, 8, N'Quilleco', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (199, 8, N'Quilaco', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (200, 8, N'Nacimiento', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (201, 8, N'Negrete', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (202, 8, N'Antuco', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (203, 8, N'Lebu', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (204, 8, N'Curanilahue', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (205, 8, N'Tirúa', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (206, 8, N'Los Ángeles', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (207, 8, N'Cabrero', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (208, 8, N'Mulchén', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (209, 9, N'Angol', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (210, 9, N'Los Sauces', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (211, 9, N'Renaico', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (212, 9, N'Collipulli', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (213, 9, N'Ercilla', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (214, 9, N'Traiguén', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (215, 9, N'Lumaco', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (216, 9, N'Victoria', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (217, 9, N'Curacautín', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (218, 9, N'Lonquimay', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (219, 9, N'Temuco', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (220, 9, N'Lautaro', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (221, 9, N'Perquenco', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (222, 9, N'Galvarino', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (223, 9, N'Nueva Imperial', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (224, 9, N'Carahue', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (225, 9, N'Freire', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (226, 9, N'Vilcún', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (227, 9, N'Cunco', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (228, 9, N'Pitrufquén', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (229, 9, N'Gorbea', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (230, 9, N'Toltén', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (231, 9, N'Loncoche', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (232, 9, N'Villarrica', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (233, 9, N'Pucón', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (234, 9, N'Curarrehue', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (235, 9, N'Melipeuco', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (236, 9, N'Teodoro Schmidt', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (237, 14, N'Valdivia', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (238, 14, N'Mariquina', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (239, 14, N'Lanco', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (240, 14, N'Los Lagos', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (241, 14, N'Futrono', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (242, 14, N'Corral', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (243, 14, N'MAFIL', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (244, 14, N'Panguipulli', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (245, 14, N'La Union', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (246, 14, N'Paillaco', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (247, 14, N'Rio Bueno', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (248, 14, N'Lago Ranco', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (249, 10, N'Osorno', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (250, 10, N'San Pablo', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (251, 10, N'Puerto Octay', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (252, 10, N'Rio Negro', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (253, 10, N'Purranque', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (254, 10, N'San Juan De La Costa', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (255, 10, N'Puerto Montt', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (256, 10, N'Cochamo', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (257, 10, N'Calbuco', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (258, 10, N'Maullin', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (259, 10, N'Los Muermos', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (260, 10, N'Fresia', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (261, 10, N'Frutillar', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (262, 10, N'Llanquihue', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (263, 10, N'Puerto Varas', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (264, 10, N'Castro', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (265, 10, N'Ancud', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (266, 10, N'Quemchi', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (267, 10, N'Quinchao', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (268, 10, N'Curaco De Velez', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (269, 10, N'Dalcahue', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (270, 10, N'Chonchi', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (271, 10, N'Puqueldon', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (272, 10, N'Queilen', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (273, 10, N'Quellon', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (274, 10, N'Palena', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (275, 10, N'Chaiten', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (276, 10, N'Futaleufu', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (277, 10, N'Hualaihue', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (278, 11, N'Puerto Aysen', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (279, 11, N'Cisne', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (280, 11, N'Guaitecas', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (281, 11, N'Chile Chico', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (282, 11, N'Rio Ibañez', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (283, 11, N'Cochrane', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (284, 11, N'Ohiggins', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (285, 11, N'Tortel', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (286, 11, N'Coyhaique', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (287, 11, N'Lago Verde', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (288, 12, N'Puerto Natales', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (289, 12, N'Torre Del Paine', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (290, 12, N'Punta Arenas', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (291, 12, N'Laguna Blanca', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (292, 12, N'Rio Verde', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (293, 12, N'San Gregorio', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (294, 12, N'Porvenir', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (295, 12, N'Timaukel', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (296, 12, N'Cabo de Hornos (Ex - Navarino)', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (297, 12, N'Antartica', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (298, 13, N'Colina', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (299, 13, N'Lampa', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (300, 13, N'Tiltil', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (301, 13, N'Puente Alto', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (302, 13, N'Pirque', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (303, 13, N'San Jose De Maipo', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (304, 13, N'San Bernardo', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (305, 13, N'Buin', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (306, 13, N'Paine', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (307, 13, N'Calera De Tango', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (308, 13, N'Talagante', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (309, 13, N'Peñaflor', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (310, 13, N'El Monte', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (311, 13, N'Isla De Maipo', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (312, 13, N'Melipilla', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (313, 13, N'Maria Pinto', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (314, 13, N'San Pedro', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (315, 13, N'Curacavi', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (316, 13, N'Alhué', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (317, 2, N'Antofagasta', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (318, 2, N'Mejillones', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (319, 2, N'Sierra Gorda', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (320, 2, N'Taltal', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (321, 2, N'Tocopilla', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (322, 2, N'María Elena', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (323, 3, N'Chañaral', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (324, 3, N'Diego De Almagro', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (325, 3, N'Copiapó', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (326, 3, N'Caldera', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (327, 3, N'Tierra Amarilla', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (328, 3, N'Huasco', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (329, 3, N'Vallenar', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (330, 3, N'Freirina', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (331, 3, N'Alto Del Carmen', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (332, 9, N'Purén', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (333, 8, N'Santa Bárbara', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (334, 8, N'Chiguayante', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (335, 7, N'San Rafael', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (336, 12, N'Primavera', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (337, 8, N'Chillán Viejo', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (338, 5, N'Concón', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (339, 10, N'Puyehue', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (340, 9, N'Padre Las Casas', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (341, 8, N'San Pedro De La Paz', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (342, 9, N'Saavedra', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (343, 13, N'Padre Hurtado', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (344, 8, N'Hualpén', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (345, 1, N'Alto Hospicio', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (346, 8, N'Alto Biobío', 0)
GO
INSERT [dbo].[COM_COMUNA] ([ID], [REG_ID], [NOMBRE], [ELIMINADO]) VALUES (347, 9, N'Cholchol', 0)
GO
SET IDENTITY_INSERT [dbo].[COM_COMUNA] OFF
GO
SET IDENTITY_INSERT [dbo].[CPO_CUPO] ON 

GO
INSERT [dbo].[CPO_CUPO] ([ID], [SGH_ID], [FECHA_HORA_INICIO], [FECHA_HORA_TERMINO], [ESTADO_CUPO], [DESCRIPCION], [ELIMINADO], [ACTIVO], [NOD_ID], [PROF_ID], [CLIE_ID], [FECHA_HORA_REGISTRO]) VALUES (1, 1, CAST(N'2016-07-09 10:00:00.000' AS DateTime), CAST(N'2016-07-09 10:45:00.000' AS DateTime), 1, N'Clase', 0, 1, 1, 1, 1, CAST(N'2016-07-09 17:38:00.000' AS DateTime))
GO
INSERT [dbo].[CPO_CUPO] ([ID], [SGH_ID], [FECHA_HORA_INICIO], [FECHA_HORA_TERMINO], [ESTADO_CUPO], [DESCRIPCION], [ELIMINADO], [ACTIVO], [NOD_ID], [PROF_ID], [CLIE_ID], [FECHA_HORA_REGISTRO]) VALUES (2, 1, CAST(N'2016-07-27 10:00:00.000' AS DateTime), CAST(N'2016-07-27 10:45:00.000' AS DateTime), 1, N'', 0, 1, 1, 1, 0, CAST(N'2016-07-26 15:56:08.457' AS DateTime))
GO
INSERT [dbo].[CPO_CUPO] ([ID], [SGH_ID], [FECHA_HORA_INICIO], [FECHA_HORA_TERMINO], [ESTADO_CUPO], [DESCRIPCION], [ELIMINADO], [ACTIVO], [NOD_ID], [PROF_ID], [CLIE_ID], [FECHA_HORA_REGISTRO]) VALUES (9, 1, CAST(N'2016-08-04 10:00:00.000' AS DateTime), CAST(N'2016-08-04 10:45:00.000' AS DateTime), 1, N'', 0, 1, 1, 1, 0, CAST(N'2016-08-03 10:37:16.437' AS DateTime))
GO
INSERT [dbo].[CPO_CUPO] ([ID], [SGH_ID], [FECHA_HORA_INICIO], [FECHA_HORA_TERMINO], [ESTADO_CUPO], [DESCRIPCION], [ELIMINADO], [ACTIVO], [NOD_ID], [PROF_ID], [CLIE_ID], [FECHA_HORA_REGISTRO]) VALUES (10, 2, CAST(N'2016-08-04 11:15:00.000' AS DateTime), CAST(N'2016-08-04 12:05:00.000' AS DateTime), 1, N'', 0, 1, 1, 1, 0, CAST(N'2016-08-03 10:37:16.503' AS DateTime))
GO
INSERT [dbo].[CPO_CUPO] ([ID], [SGH_ID], [FECHA_HORA_INICIO], [FECHA_HORA_TERMINO], [ESTADO_CUPO], [DESCRIPCION], [ELIMINADO], [ACTIVO], [NOD_ID], [PROF_ID], [CLIE_ID], [FECHA_HORA_REGISTRO]) VALUES (11, 3, CAST(N'2016-08-04 13:30:00.000' AS DateTime), CAST(N'2016-08-04 14:15:00.000' AS DateTime), 1, N'', 0, 1, 1, 1, 0, CAST(N'2016-08-03 10:37:16.507' AS DateTime))
GO
INSERT [dbo].[CPO_CUPO] ([ID], [SGH_ID], [FECHA_HORA_INICIO], [FECHA_HORA_TERMINO], [ESTADO_CUPO], [DESCRIPCION], [ELIMINADO], [ACTIVO], [NOD_ID], [PROF_ID], [CLIE_ID], [FECHA_HORA_REGISTRO]) VALUES (12, 4, CAST(N'2016-08-04 14:45:00.000' AS DateTime), CAST(N'2016-08-04 15:30:00.000' AS DateTime), 1, N'', 0, 1, 1, 1, 0, CAST(N'2016-08-03 10:37:16.507' AS DateTime))
GO
INSERT [dbo].[CPO_CUPO] ([ID], [SGH_ID], [FECHA_HORA_INICIO], [FECHA_HORA_TERMINO], [ESTADO_CUPO], [DESCRIPCION], [ELIMINADO], [ACTIVO], [NOD_ID], [PROF_ID], [CLIE_ID], [FECHA_HORA_REGISTRO]) VALUES (13, 5, CAST(N'2016-08-04 16:00:00.000' AS DateTime), CAST(N'2016-08-04 16:45:00.000' AS DateTime), 1, N'', 0, 1, 1, 1, 0, CAST(N'2016-08-03 10:37:16.507' AS DateTime))
GO
INSERT [dbo].[CPO_CUPO] ([ID], [SGH_ID], [FECHA_HORA_INICIO], [FECHA_HORA_TERMINO], [ESTADO_CUPO], [DESCRIPCION], [ELIMINADO], [ACTIVO], [NOD_ID], [PROF_ID], [CLIE_ID], [FECHA_HORA_REGISTRO]) VALUES (14, 6, CAST(N'2016-08-04 17:15:00.000' AS DateTime), CAST(N'2016-08-04 18:00:00.000' AS DateTime), 1, N'', 0, 1, 1, 1, 0, CAST(N'2016-08-03 10:37:16.510' AS DateTime))
GO
INSERT [dbo].[CPO_CUPO] ([ID], [SGH_ID], [FECHA_HORA_INICIO], [FECHA_HORA_TERMINO], [ESTADO_CUPO], [DESCRIPCION], [ELIMINADO], [ACTIVO], [NOD_ID], [PROF_ID], [CLIE_ID], [FECHA_HORA_REGISTRO]) VALUES (15, 7, CAST(N'2016-08-04 18:30:00.000' AS DateTime), CAST(N'2016-08-04 19:15:00.000' AS DateTime), 1, N'', 0, 1, 1, 1, 0, CAST(N'2016-08-03 10:37:16.510' AS DateTime))
GO
INSERT [dbo].[CPO_CUPO] ([ID], [SGH_ID], [FECHA_HORA_INICIO], [FECHA_HORA_TERMINO], [ESTADO_CUPO], [DESCRIPCION], [ELIMINADO], [ACTIVO], [NOD_ID], [PROF_ID], [CLIE_ID], [FECHA_HORA_REGISTRO]) VALUES (16, 1, CAST(N'2016-08-05 10:00:00.000' AS DateTime), CAST(N'2016-08-05 10:45:00.000' AS DateTime), 1, N'', 0, 1, 1, 1, 0, CAST(N'2016-08-03 17:57:46.227' AS DateTime))
GO
INSERT [dbo].[CPO_CUPO] ([ID], [SGH_ID], [FECHA_HORA_INICIO], [FECHA_HORA_TERMINO], [ESTADO_CUPO], [DESCRIPCION], [ELIMINADO], [ACTIVO], [NOD_ID], [PROF_ID], [CLIE_ID], [FECHA_HORA_REGISTRO]) VALUES (17, 2, CAST(N'2016-08-05 11:15:00.000' AS DateTime), CAST(N'2016-08-05 12:05:00.000' AS DateTime), 1, N'', 0, 1, 1, 1, 0, CAST(N'2016-08-03 17:58:29.920' AS DateTime))
GO
INSERT [dbo].[CPO_CUPO] ([ID], [SGH_ID], [FECHA_HORA_INICIO], [FECHA_HORA_TERMINO], [ESTADO_CUPO], [DESCRIPCION], [ELIMINADO], [ACTIVO], [NOD_ID], [PROF_ID], [CLIE_ID], [FECHA_HORA_REGISTRO]) VALUES (18, 3, CAST(N'2016-08-05 13:30:00.000' AS DateTime), CAST(N'2016-08-05 14:15:00.000' AS DateTime), 1, N'', 0, 1, 1, 1, 0, CAST(N'2016-08-03 17:58:47.790' AS DateTime))
GO
INSERT [dbo].[CPO_CUPO] ([ID], [SGH_ID], [FECHA_HORA_INICIO], [FECHA_HORA_TERMINO], [ESTADO_CUPO], [DESCRIPCION], [ELIMINADO], [ACTIVO], [NOD_ID], [PROF_ID], [CLIE_ID], [FECHA_HORA_REGISTRO]) VALUES (19, 4, CAST(N'2016-08-05 14:45:00.000' AS DateTime), CAST(N'2016-08-05 15:30:00.000' AS DateTime), 1, N'', 0, 1, 1, 1, 0, CAST(N'2016-08-04 10:39:59.757' AS DateTime))
GO
INSERT [dbo].[CPO_CUPO] ([ID], [SGH_ID], [FECHA_HORA_INICIO], [FECHA_HORA_TERMINO], [ESTADO_CUPO], [DESCRIPCION], [ELIMINADO], [ACTIVO], [NOD_ID], [PROF_ID], [CLIE_ID], [FECHA_HORA_REGISTRO]) VALUES (20, 5, CAST(N'2016-08-05 16:00:00.000' AS DateTime), CAST(N'2016-08-05 16:45:00.000' AS DateTime), 1, N'', 0, 1, 1, 1, 0, CAST(N'2016-08-04 10:39:59.917' AS DateTime))
GO
INSERT [dbo].[CPO_CUPO] ([ID], [SGH_ID], [FECHA_HORA_INICIO], [FECHA_HORA_TERMINO], [ESTADO_CUPO], [DESCRIPCION], [ELIMINADO], [ACTIVO], [NOD_ID], [PROF_ID], [CLIE_ID], [FECHA_HORA_REGISTRO]) VALUES (21, 6, CAST(N'2016-08-05 17:15:00.000' AS DateTime), CAST(N'2016-08-05 18:00:00.000' AS DateTime), 1, N'', 0, 1, 1, 1, 1, CAST(N'2016-08-04 10:41:29.543' AS DateTime))
GO
SET IDENTITY_INSERT [dbo].[CPO_CUPO] OFF
GO
SET IDENTITY_INSERT [dbo].[NOD_NODO] ON 

GO
INSERT [dbo].[NOD_NODO] ([ID], [NOMBRE], [DIRECCION], [PAI_ID], [REG_ID], [COM_ID], [EMAIL], [TELEFONO_CONTACTO_1], [TELEFONO_CONTACTO_2], [ACTIVO], [ELIMINADO]) VALUES (1, N'Sin Alitas .cl', N'No Informada', 1, 13, 301, N'administracion@sinalitas.cl', N'85006988', N' ', 1, 0)
GO
SET IDENTITY_INSERT [dbo].[NOD_NODO] OFF
GO
SET IDENTITY_INSERT [dbo].[PAI_PAIS] ON 

GO
INSERT [dbo].[PAI_PAIS] ([ID], [NOMBRE], [ELIMINADO]) VALUES (1, N'Chile', 0)
GO
SET IDENTITY_INSERT [dbo].[PAI_PAIS] OFF
GO
SET IDENTITY_INSERT [dbo].[PROF_PROFESOR] ON 

GO
INSERT [dbo].[PROF_PROFESOR] ([ID], [RUT], [NOMBRES], [PRIMER_APELLIDO], [SEGUNDO_APELLIDO], [FOTOGRAFIA], [CODIGO], [PAI_ID], [REG_ID], [COM_ID], [DIRECCION], [SEXO], [FECHA_NACIMIENTO], [NOMBRE_USUARIO], [PASSWORD], [ACTIVO], [ELIMINADO], [TELEFONOS_CONTACTO], [BANCO], [TIPO_CUENTA], [NUMERO_CUENTA], [EMAIL], [NOD_ID]) VALUES (1, N'12535306-1', N'Victor', N'Coronado', N'Alarcón', NULL, N'12535306', 1, 13, 6, N'Prueba', N'Masculino', CAST(N'1973-01-24 00:00:00.000' AS DateTime), N'vcoronado', N'123456', 1, 0, N'85006988', N'Estado', 1, N'12535306', N'vcoronado.alarcon@gmail.com', 1)
GO
SET IDENTITY_INSERT [dbo].[PROF_PROFESOR] OFF
GO
SET IDENTITY_INSERT [dbo].[REG_REGION] ON 

GO
INSERT [dbo].[REG_REGION] ([ID], [PAI_ID], [NOMBRE], [ELIMINADO]) VALUES (1, 1, N'I Región Tarapaca', 0)
GO
INSERT [dbo].[REG_REGION] ([ID], [PAI_ID], [NOMBRE], [ELIMINADO]) VALUES (2, 1, N'II Región Antofagasta', 0)
GO
INSERT [dbo].[REG_REGION] ([ID], [PAI_ID], [NOMBRE], [ELIMINADO]) VALUES (3, 1, N'III Región Atacama', 0)
GO
INSERT [dbo].[REG_REGION] ([ID], [PAI_ID], [NOMBRE], [ELIMINADO]) VALUES (4, 1, N'IV Región Coquimbo', 0)
GO
INSERT [dbo].[REG_REGION] ([ID], [PAI_ID], [NOMBRE], [ELIMINADO]) VALUES (5, 1, N'V Región  Valparaiso', 0)
GO
INSERT [dbo].[REG_REGION] ([ID], [PAI_ID], [NOMBRE], [ELIMINADO]) VALUES (6, 1, N'VI Región Lib. Bernardo O`Higgins', 0)
GO
INSERT [dbo].[REG_REGION] ([ID], [PAI_ID], [NOMBRE], [ELIMINADO]) VALUES (7, 1, N'VII Región Maule', 0)
GO
INSERT [dbo].[REG_REGION] ([ID], [PAI_ID], [NOMBRE], [ELIMINADO]) VALUES (8, 1, N'VIII Región Bío-Bío', 0)
GO
INSERT [dbo].[REG_REGION] ([ID], [PAI_ID], [NOMBRE], [ELIMINADO]) VALUES (9, 1, N'IX Región Araucania', 0)
GO
INSERT [dbo].[REG_REGION] ([ID], [PAI_ID], [NOMBRE], [ELIMINADO]) VALUES (10, 1, N'X Región Los Lagos', 0)
GO
INSERT [dbo].[REG_REGION] ([ID], [PAI_ID], [NOMBRE], [ELIMINADO]) VALUES (11, 1, N'XI Región Aysén', 0)
GO
INSERT [dbo].[REG_REGION] ([ID], [PAI_ID], [NOMBRE], [ELIMINADO]) VALUES (12, 1, N'XII Región Magallanes', 0)
GO
INSERT [dbo].[REG_REGION] ([ID], [PAI_ID], [NOMBRE], [ELIMINADO]) VALUES (13, 1, N'XIII Región Metropolitana', 0)
GO
INSERT [dbo].[REG_REGION] ([ID], [PAI_ID], [NOMBRE], [ELIMINADO]) VALUES (14, 1, N'XIV Región de los Ríos', 0)
GO
INSERT [dbo].[REG_REGION] ([ID], [PAI_ID], [NOMBRE], [ELIMINADO]) VALUES (15, 1, N'XV Región de Arica y Parinacota', 0)
GO
SET IDENTITY_INSERT [dbo].[REG_REGION] OFF
GO
SET IDENTITY_INSERT [dbo].[SGH_SEGMENTO_HORARIO] ON 

GO
INSERT [dbo].[SGH_SEGMENTO_HORARIO] ([ID], [NOD_ID], [DURACION_ATENCION], [FECHA_HORA_INICIAL], [FECHA_HORA_FINAL], [ACTIVO], [ELIMINADO]) VALUES (1, 1, 45, CAST(N'2016-07-04 10:00:00.000' AS DateTime), CAST(N'2016-07-14 10:45:00.000' AS DateTime), 1, 0)
GO
INSERT [dbo].[SGH_SEGMENTO_HORARIO] ([ID], [NOD_ID], [DURACION_ATENCION], [FECHA_HORA_INICIAL], [FECHA_HORA_FINAL], [ACTIVO], [ELIMINADO]) VALUES (2, 1, 45, CAST(N'2016-07-14 11:15:00.000' AS DateTime), CAST(N'2016-07-14 12:05:00.000' AS DateTime), 1, 0)
GO
INSERT [dbo].[SGH_SEGMENTO_HORARIO] ([ID], [NOD_ID], [DURACION_ATENCION], [FECHA_HORA_INICIAL], [FECHA_HORA_FINAL], [ACTIVO], [ELIMINADO]) VALUES (3, 1, 45, CAST(N'2016-07-14 13:30:00.000' AS DateTime), CAST(N'2016-07-14 14:15:00.000' AS DateTime), 1, 0)
GO
INSERT [dbo].[SGH_SEGMENTO_HORARIO] ([ID], [NOD_ID], [DURACION_ATENCION], [FECHA_HORA_INICIAL], [FECHA_HORA_FINAL], [ACTIVO], [ELIMINADO]) VALUES (4, 1, 45, CAST(N'2016-07-14 14:45:00.000' AS DateTime), CAST(N'2016-07-14 15:30:00.000' AS DateTime), 1, 0)
GO
INSERT [dbo].[SGH_SEGMENTO_HORARIO] ([ID], [NOD_ID], [DURACION_ATENCION], [FECHA_HORA_INICIAL], [FECHA_HORA_FINAL], [ACTIVO], [ELIMINADO]) VALUES (5, 1, 45, CAST(N'2016-07-14 16:00:00.000' AS DateTime), CAST(N'2016-07-14 16:45:00.000' AS DateTime), 1, 0)
GO
INSERT [dbo].[SGH_SEGMENTO_HORARIO] ([ID], [NOD_ID], [DURACION_ATENCION], [FECHA_HORA_INICIAL], [FECHA_HORA_FINAL], [ACTIVO], [ELIMINADO]) VALUES (6, 1, 45, CAST(N'2016-07-14 17:15:00.000' AS DateTime), CAST(N'2016-07-14 18:00:00.000' AS DateTime), 1, 0)
GO
INSERT [dbo].[SGH_SEGMENTO_HORARIO] ([ID], [NOD_ID], [DURACION_ATENCION], [FECHA_HORA_INICIAL], [FECHA_HORA_FINAL], [ACTIVO], [ELIMINADO]) VALUES (7, 1, 45, CAST(N'2016-07-14 18:30:00.000' AS DateTime), CAST(N'2016-07-14 19:15:00.000' AS DateTime), 1, 0)
GO
SET IDENTITY_INSERT [dbo].[SGH_SEGMENTO_HORARIO] OFF
GO
