SELECT * FROM PCO_PRODUCTO_CODIGO
--UPDATE PCO_PRODUCTO_CODIGO SET ACTIVO = 0

SELECT * FROM CPO_CUPO
--TRUNCATE TABLE CPO_CUPO

SELECT * FROM ACC_ACEPTA_CONDICIONES
-- TRUNCATE TABLE ACC_ACEPTA_CONDICIONES

SELECT * FROM FIA_FICHA_ALUMNO

SELECT * FROM FIP_FICHA_PACK

SELECT * FROM OBP_OBSERVACIONES_PROFESOR
--TRUNCATE TABLE OBP_OBSERVACIONES_PROFESOR

/* HAY QUE MODIFICAR LOS PROFESORES Y LOS PRODUCTOS, REVISAR LOS SEGMENTOS HORARIOS */
